### ISSUE TITLE
Tracking issue for Generic Associated Types support

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#10187]
This should be reconsidered/reprioritized with this blog post in mind: https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html

- [x] Update inspections for Type Aliase #7976
- [x] Render generic parameters for associated types in `Implement Members` #7977
- [x] Parse of generic parameters for assoc types / type aliases and assoc type bindings #8542
- [x] Basic type inference for GATs #8544
- [x] Render generic parameters for assoc types if any #8565
- [x] Support new `where` clause location for associated types #8826
- [ ] Wrong type inference with GATs #9896
