### ISSUE TITLE
Extend method function extraction

### ISSUE THREAD

**Issue by farodin91** [intellij-rust/intellij-rust#1553]
Currently, method extraction can only extract the contain code.

### Todo
- [x] Support input parameter
- [x] Support return parameter
- [ ] Edit function header, like kotlin method extraction

**Comment by Undin** [comment]
@farodin91 Let's close this issue - #2183 looks more detailed
