### ISSUE TITLE
Auto import

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2174]
Meta issue to support auto import:
- [x] Naive support (without reexports) as intention
- [x] Support reexports
- [x] Convert intention to inspection with quick fix
- [x] Unimported methods from impls
- [x] Suggest import while typing ~~#789~~ ~~#2721~~
- [x] Import trait while trait method completion

Related issues:
* ~~#789~~
* ~~#1366~~
* ~~#1488~~
* ~~#1737~~
* ~~#2034~~
* ~~#2157~~
* ~~#2159~~
* ~~#2299~~
* ~~#2347~~ 
* ~~#2367~~
* ~~#2388~~
* ~~#2394~~
* ~~#2402~~
* #2438
* ~~#2444~~
* ~~#2721~~
* ~~#2822~~
* ~~#2889~~
* ~~#3269~~
* ~~#3275~~

**Comment by Undin** [comment]
Looks like we've implemented all subissues
