### ISSUE TITLE
Import Optimizer

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2259]
Meta issue to support import optimizer:

* [x] Sort use speck in use item
* [x] Sort different import items
* [x] Sort `extren crate` items
* [ ] Collapse imports when possible
* [ ] Remove unused imports
* [x] Group imports by semantics (std, crates, inner mods, etc.)

Related issues:
#2158
~~#2248~~ 
~~#2276~~
~~#2519~~
~~#2577~~
~~#2929~~

**Comment by farodin91** [comment]
Possible other tasks?
* grouping into semantic imports (std, crates, inner mods) (no trivial)
* sort _mod_ and _extern crate_

**Comment by Undin** [comment]
I'm not sure about mod sorting because it's not about items import
Other suggestions sound good)

**Comment by farodin91** [comment]
For extern crate: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#reorder_extern_crates (possible also in groups)
For grouping of imports: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md#reorder_imports_in_group
I thought of 
```rust
mod a;
mod b;
mod c;
```

**Comment by Undin** [comment]
Yeah, I've understood your idea
I think mod reordering is not very good idea for `Optimize Import` action because it's quite unexpected thing for user while import optimizing
It can be part of other action (for example, formatting) or separate action or something else

**Comment by farodin91** [comment]
Okay

**Comment by farodin91** [comment]
#2277

**Comment by Undin** [comment]
@farodin91 looks like that it's formatter bug - import optimizer works correctly in this case

**Comment by farodin91** [comment]
I wanted to link #2276.

**Comment by przygienda** [comment]
minor but annoying: 

in extern create X as Y 

auto import 

does use X::v 

instead of 

use Y::v

**Comment by Undin** [comment]
@przygienda It's not related to import optimizer
I've created separate issue #2444

**Comment by U007D** [comment]
IntelliJ Rust gets better with each release, thank you everyone!

I've noticed that `Optimize Imports` places `use` statements first followed by `mod` statements.  I would like the inverse order--`mods` then `use` (as my `use` path statements often depend on the `mod`.  As a reviewer, this is easier to follow when it's not in 'forward-declaration format').  Is that configurable somewhere or is it hard-coded?

**Comment by BillOTei** [comment]
installed it on Clion and Idea ultimate, it does not seem to remove unused imports, is it normal?

**Comment by Undin** [comment]
@BillOTei unused import detection is not yet implemented. As a result, "Optimize imports" action doesn't remove them. BTW there is the corresponding item in issue description

**Comment by BillOTei** [comment]
> @BillOTei unused import detection is not yet implemented. As a result, "Optimize imports" action doesn't remove them. BTW there is the corresponding item in issue description

thks nvm sorry for not reading thoroughly.

**Comment by trivigy** [comment]
@Undin do you happen to know what is the state of this issue? Anyway to control this ordering via some configurations?

**Comment by MixusMinimax** [comment]
A bit of a problem: in order to use a macro in the same crate across modules, you need to define the macro, and _then_ do
```rust
pub(crate) use my_macro;
```
moving the `use` to the top of the file breaks that.
