### ISSUE TITLE
Support Rust 2018 edition

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#2622]
[Edition guide](https://rust-lang-nursery.github.io/edition-guide/2018)

* [x] `impl Trait`
* [ ] `dyn Trait`
  * [x] parser and type inference support
  * [ ] inspection and quick fix to convert bare trait object type to `dyn Trait`
* [ ] module system
  * [ ] resolution without `extern crate` item
  * [ ] absolute path started from crate name or `crate`
  * [ ] `crate` visibility modifier
  * [ ] module hierarchy without `mod.rs` file
  * [ ] (re)export macro via `use` item
* [ ] async/await
* [ ] ownership and lifetimes
  * [ ] anonymous lifetime
  * [ ] in-band lifetimes
  * [ ] lifetime elision in impl
  * [ ] default match bindings
* [ ] slice patterns
* [ ] raw identifiers
* [ ] keywords
  * [ ] `async`, `await` and `try` should be keyword in 2018 edition
  * [ ] `proc` is not keyword anymore

**Comment by jannik17** [comment]
I think [this cargo feature to rename a crate](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#cargo-features) is missing in the list.

**Comment by Undin** [comment]
@jannik17 Yep, you are absolutely right
I've added the corresponding point

**Comment by SomeoneToIgnore** [comment]
It looks like `edition` TOML field support is not mentioned here also.
I've created a PR to add the missing functionality, hope it will be useful: https://github.com/intellij-rust/intellij-rust/pull/3214

**Comment by brokenthorn** [comment]
Seems like there's no type inference or autocomplete for all `pub async fn`.

For example, the `pub async fn text(self)` in reqwest's `Response` struct:

```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let response_future = reqwest::get("https://httpbin.org/ip");
    let response = response_future.await?;
    let text_future = response.text();
    let text = text_future.await?;
    println!("{:#?}", text);
    Ok(())
}
```

![image](https://user-images.githubusercontent.com/2119004/70816416-2048ba00-1dd8-11ea-9dc1-968b8ff4807c.png)

Cargo dependencies:
```toml
[dependencies]
reqwest = "0.10.0-alpha.2"
tokio = "0.2.0-alpha.6"
futures = "0.3.1"
chrono = "0.4.10"
```

[`text(self)` is part of `impl Response`](https://docs.rs/reqwest/0.10.0-alpha.2/reqwest/struct.Response.html#method.text) so this is not because I'm not importing the right `Trait`.

**Comment by Undin** [comment]
> Seems like there's no type inference or autocomplete for all pub async fn

@brokenthorn no, it's not related to async function at all. The cause why name resolution fails here is that part of `reqwest ` modules are declared under [macro call](https://github.com/seanmonstar/reqwest/blob/master/src/lib.rs#L267-L307) that cannot be handled by default in IntelliJ Rust plugin.
Try to enabled the experimental macro expansion engine (see #3628). It should fix your issue
Note, there are some issues like #4627 when modules are declared under several macro calls. In such cases, new expansion engine can't process them too for now. The most known crates are `tokio` and `async_std`

**Comment by brokenthorn** [comment]
@Undin, Well, gosh darn it, doesn't this suck. Thanks. I'll keep this thing in mind. Seems like Rust IDEs still have a ways to go before IJW™️...
