### ISSUE TITLE
Support Rust 1.30 features

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#2986]
[Rust 1.30 blogpost](https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html)

- [ ] import macros by `use` item without `#[macro_use]` (use_extern_macros)
- [ ] new syntax for macros `foo::bar!()`
- [x] paths start with crate name (2015 edition) #2987
- [x] paths start with `crate` keyword (2015 edition)
- [x] raw identifiers (2015 edition)
- [x] `vis` macro fragment specifier
