### ISSUE TITLE
Debugger pretty printers

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3000]
This issue is just an overview of current known issues related to debugger pretty printers for `gdb` and `lldb`

* [ ] scalar types
  * [ ] show correct names of scalar types: `u32`, `i16`, etc instead of C/C++ names like `unsigned int`, `short`, etc
  * [ ] lldb considers that `i8` and `u8` are `char` and `unsigned char` respectevely and converts values of these types to symbols
  * [ ] `char` type now is shows as `void` without any value
* [ ] arrays and slices
  * [ ] correct type names
  * [ ] only size in summary
* [ ] tuples
  * [ ] don't show fields values in summary
  * [ ] show `i` instead of  `__i` as field name
* [ ] structs
  * [ ] don't show fields values in summary
* [ ] enums/enum variants
  * [ ] don't show fields values in summary
  * [ ] correctly determine enum variant
  * [ ] provide only related to current enum variant fields
* [ ] references
  * [ ] show correct type names like `&i32` instead of `int *`
  * [ ] show summary of dereferenced value of reference
* [ ] pointers
  * [ ] show correct type names like `*i32` instead of `int *`
* [ ] `Vec`
  * [ ] show only size of vector instead of `vec![item1, item2, ...]` string in summary
  * [ ] show indexed children instead of `buf` and `len` fields
* [ ] `Rc` and `Arc`
  * [ ] show `strong`, `week` and summary of dereferenced value
* [ ] Box
  * [ ] show correct type (`Box<i32>` instead of `int *`)
  * [ ] show summary of dereferenced value

**Comment by DezzK** [comment]
I think, debugger issues are the most annoying at this moment.

**Comment by Undin** [comment]
@DezzK what do you mean?

**Comment by DezzK** [comment]
@Undin I mean, the plugin works pretty good for me (excepting debugging, macro support and several not so serious issues). But still the most annoying of issues is debugging support. Despite it works much better than several months ago, it is still needed to add dbg!(...) macro or other logging just to print variable value in part of cases because not watching, nor expression evaluation can help at these cases. Perhaps it is specific to our project, because we activelly use enums and enum variants with data in them, which are not supported yet by the plugin (I mean that printers for enum variants are not implemented yet).

BTW, using enum variants is the Rust way, it's not a kind of rarely using features. I will be appreciated, if you implement a support of enum variants in the debugger soon. I think, showing variable value in debugger is much more meaningful than showing correct type names and so on. :)

Thanks

**Comment by xrl** [comment]
Would it be possible to pretty print strings behind a reference? I'm inside an iterator loop and I have a variable `name: &String` and the Variables pane in the debugger shows a Vec<u8> which is not very useful.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/693059/102636946-ab673900-412b-11eb-95ac-0533e718ed37.png">

<img width="581" alt="image" src="https://user-images.githubusercontent.com/693059/102636970-b5893780-412b-11eb-95c6-dfa7a622d640.png">

it would be great if it showed the string contents like other contexts

**Comment by kevleyski** [comment]
I'm with @xrl - would be good to present vectors as a string (or at least show the char equiv of each byte)

**Comment by vjpr** [comment]
Is it possible to get `string_cache::Atom` support?

**Comment by ortem** [comment]
@vjpr IntelliJ Rust bundled pretty-printers are mostly aimed at supporting built-in and stdlib types. You can extend them manually by implementing new providers as described [here](https://github.com/intellij-rust/intellij-rust/issues/3639#issuecomment-480232986). The implementation may look like [this](https://github.com/intellij-rust/intellij-rust/pull/5270). Also, in order to use custom pretty-printers with LLDB, you should enable them by adding the following lines to [`.lldbinit`](https://www.jetbrains.com/help/clion/configuring-debugger-options.html#gdbinit-lldbinit):
```
type synthetic add -l lldb_lookup.synthetic_lookup -x "<type regex>" --category Rust
type summary add -F lldb_lookup.summary_lookup  -e -x -h "<type regex>" --category Rust
```

**Comment by Leptis** [comment]
Hey! I was just dealing with Options being too hard to debug in debugger and noticed a mistake in lldb rust_type.py which provideы regexps for rust types now. Regexp for Options is r"^core::option::Option<.+>::(Some|None)$" there but it is not being triggered becaurse in fact the Option path to match is "enum2$<core::option::Option<ref$<str$> > >". So the regexp should be like r"^enum2\$<core::option::Option<.+>::(Some|None)$" instead. And btw it would be really grate to have that synth provider in addition to the summary one right out of the box
