### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by NeverGivinUp** [intellij-rust/intellij-rust#3066]
Are you planning to support or already supporting compiling to WASM? Where would I find instructional documentation? I think there already is some support for compiling Kotlin to WASM, so that could be an starting point for the WASM side. WASM requires Javascript support, to really do stuff in the browser. So this might be a compile target suited specifically for WebStorm-integration. Also: support for Yew would be great.

---

## META TODO

Feature support list:
- [x] WebAssembly projects creation in `New project` dialog
  - [x] `cargo-generate` templates
  - [ ] Native Cargo templates https://github.com/rust-lang/rfcs/pull/2922
- [x] `wasm-pack` run configurations
  - [x] Commands completion
  - [x] Build tool window for `build` and `test` commands
- [x] `wasm-pack` commands in `Run Anything`
- [ ] `wasm-bindgen` tests #3007
- [ ] Rust <-> JS interop
  - [x] Rust->JS navigation
  - [ ] JS->Rust navigation
  - [ ] Cross-language refactorings support
- [ ] npm integration
  - [ ] Set up a web page using `npm init wasm-app` and `npm install`
  - [ ] Provide run configuration `npm run start`
- [ ] Debugging of WebAssembly projects
  - [ ] Plain Rust+Wasm web projects
  - [ ] Rust+Wasm web projects with wasm-bindgen (blocked by https://github.com/rustwasm/wasm-bindgen/issues/2389)
  - [ ] Debugging when running in standalone runtime (e.g. `wasmtime`)
- [ ] Auto refresh/rebuild on changes (`watch` and `serve` subcommands) https://github.com/rustwasm/rfcs/pull/10
- [ ] Documentation
  - [ ] `cargo-generate`
  - [ ] `wasm-pack`

**Comment by vlad20012** [comment]
Hmm, what kind of support do you expect from IDE? "Compiling" is a responsibility of, well, the compiler =) You can find an appropriate instruction about compiling Rust to wasm in [wasm-pack](https://github.com/rustwasm/wasm-pack) or stdweb projects. If you know some specific wasm-related features you expect from our plugin, feel free to list them =)

Btw IntelliJ-Rust works in WebStorm, and IntelliJ IDE ultimate also supports JavaScript.

**Comment by NeverGivinUp** [comment]
> "Compiling" is a responsibility of, well, the compiler =)

That is certainly true! But there is also project structure, dependency management to and from Javascript libraries, packaging, deployment, debugging an app running in the browser and interacting with the DOM. You might consider separate sub project types for WASM projects, [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) written in WASM, single page apps written in [Yew](https://github.com/DenisKolodin/yew).

**Comment by vlad20012** [comment]
It's interesting. Ok, for now we made literally nothing about WASM support. And to be honest, I know too little about it. If you can describe what __exactly__ we can do to help wasm developers, feel free to open specific issues about it. For example, there is an issue about wasm test runners #3007. It could be a good issue "Support run Yew apps", for example.

**Comment by ponchofiesta** [comment]
To run wasm-pack from run configuration like Cargo would be a start.

**Comment by SnowyCoder** [comment]
The current intellij-rust does not recognize any object provided by web_sys, and that is quite annoying as that means that there is no auto-completition support.

**Comment by vlad20012** [comment]
@SnowyCoder 
There are 2 problems with `web-sys`:
1. It requires `include` macro support. We currently actively working on it, see #1908 (#3935)
2. wasm-bindgen generated too large source file for `web-sys`. IntelliJ source file size limit is about 2.5 Mb, when `web-sys`'s `bindings.rs` can be of 10 Mb in size  (depending on active features). Looks like we can't solve it on our side and it's really needed to split `web-sys`'s `bindings.rs` into multiple files on `web-sys` side. I think we'll start to discuss this possibility with `web-sys` developers when we'll finish work on `include`.

**Comment by edvorg** [comment]
On a side note. I used intellij idea to develop a web project that is made 100% (native + wasm). I used a multiproject setup, with common parts of the logic written in a shared project that is used as dependency on backend and frontend.

Surprisingly, EVERYTHING worked really well. Code completion, code navigation, refactoring in both frontend and backend. I completely did not expect it. Big thanks to developer of rust plugin!

If you're interested to checkout how the project is setup you may take a look here https://github.com/edvorg/rustmith, but there is nothing idea-specific there really. Just a standard cargo project.

**Comment by HughPH** [comment]
Thank you @edvorg , as a C# developer coming from Rider and previously VS, I'm 'spoilt' - I just want to write code, add some breakpoints and hit the 'debug' button, it's tiring having to learn so many new tools so often and I'm trying to distance myself from the ever-twisting clusterfunk that seems to be what's become of the modern JavaScript landscape.

Regarding @NeverGivinUp 's original question, my interpretation of "Integrated" Development Environment is that it "Integrates" all the tools - including whatever compilers are required. Again, back to my C# point, if I add a file type that's supported, I would expect the IDE to compile it without me having to do anything (except perhaps download the compiler of my choice and perhaps make a selection in the IDE.) Now, the Rust Plugin does do this very well for what it supports, and I'm largely delighted with how easy it is to create a command-line app in Rust and be able to debug it. But one of the main points of Rust is that you can create WASM Libraries with it (it's on the rust-lang.org front page FFS) so simply not doing anything for WASM seems to me like the ball has been dropped. Indeed, I feel quite strongly that the ball has been dropped all the way down the line: the headline is "Create WebAssembly libraries really easily!" but I find myself having to download some thing called Emscripten (for which I had to write my own update script) and arse about in the bowels of the CLion project settings to add a path, which seems to be where the scant detail available online peters out.

**Comment by panstromek** [comment]
With the latest release (116), `web_sys` intellisense works if you:

1. Enable `org.rust.cargo.evaluate.build.scripts` in experimental features
   (`double shift` -> `experimental features`)

2. Increase the filelimit (as pointed out above)
   (`help -> Custom VM options`)
   Put this line into the file: `-Didea.max.intellisense.filesize=20000`

3. Maybe restart the IDE? I think I needed to do it...

**Comment by tiberiusferreira** [comment]
It works! Absolutely fantastic! Thank you very much to everyone involved, this made my day!

**Comment by thecodewarrior** [comment]
This still isn't working for me, even with the changes @panstromek mentioned. It's not even a simple "it doesn't work" either since in some cases it _is_ kind of working, but it's working incorrectly.

I have this in my `Cargo.toml`:
```toml
[dependencies.web-sys]
version = "0.3.36"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
]
```
and here's some code that exhibits the issue:
```rust
fn foo() {
    let document: web_sys::Document = web_sys::window().unwrap().document().unwrap();
    let document: web_sys::Document = web_sys::document(web_sys::window().unwrap()).unwrap();
}
```

That code has three different parts:
- The part that does work is that it _can_ see `web_sys::window()`, presumably since it's defined in the root `lib.rs` file.
- The simple "it doesn't work" issue is that it can't seem to see (i.e. I can't "go to definition") any of the types, in this case, `web_sys::Document`.
- The part that kind of works, albeit incorrectly, is that on the first line, IntelliJ-Rust can't find the `document` function, but on the second line it can. The strange part is that the first line compiles but the second one doesn't, so IntelliJ-Rust is failing on the correct code and succeeding on the incorrect code. The function it jumps to is this one, in `gen_Window.rs`:

```rust
#[wasm_bindgen]
extern "C" {
    // ...
    #[cfg(feature = "Document")]
    # [ wasm_bindgen ( structural , method , getter , js_class = "Window" , js_name = document ) ]
    #[doc = "Getter for the `document` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/document)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Document`, `Window`*"]
    pub fn document(this: &Window) -> Option<Document>;
    // ...
}
```

My current build versions are:
- Rust nightly (`rustc 1.43.0-nightly (158127853 2020-03-10)`)
- The latest build of the IntelliJ-Rust (117) 
- The latest EAP build of IntelliJ IDEA (IntelliJ IDEA 2020.1 EAP (Ultimate Edition), Build #IU-201.6073.9)

I set the two options mentioned by @panstromek, I've tried this with both the default and experimental macro engines, and tried restarting IntelliJ all along the way. Note that when I look at the `features/mod.rs` file it does correctly highlight the enabled/disabled features (it makes the disabled features a faded "inactive" color).

## The relevant web_sys code

`web_sys`'s `lib.rs` file contains these:
```rust
mod features;
pub use features::*;

// ...

#[cfg(feature = "Window")]
pub fn window() -> Option<Window> {
```

The `features` module's `mod.rs` file contains a bunch of these:
```rust
// ...
#[cfg(feature = "Window")]
#[allow(non_snake_case)]
mod gen_Window;
#[cfg(feature = "Window")]
pub use gen_Window::*;
// ...
```

The `gen_Window` module contains a bunch of these:
```rust
#[wasm_bindgen]
extern "C" {
    // ...
    #[cfg(feature = "Document")]
    # [ wasm_bindgen ( structural , method , getter , js_class = "Window" , js_name = document ) ]
    #[doc = "Getter for the `document` field of this object."]
    #[doc = ""]
    #[doc = "[MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/document)"]
    #[doc = ""]
    #[doc = "*This API requires the following crate features to be activated: `Document`, `Window`*"]
    pub fn document(this: &Window) -> Option<Document>;
    // ...
}
```

**Comment by thecodewarrior** [comment]
I've managed to track down the root issue, and it seems to be caused by `wasm_bindgen` and #1786. Here's a minimal test case for the behavior:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen]
    fn global() -> Foo;

    type Foo;

    /// https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/constructor.html
    #[wasm_bindgen(constructor)]
    fn new() -> Foo;

    /// https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/method.html
    #[wasm_bindgen(method)]
    fn method(this: &Foo);

    /// https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/static_method_of.html
    #[wasm_bindgen(static_method_of = Foo)]
    fn static_foo() -> Foo;
}

/// This compiles, but go to definition on `Foo`, `new`, `method`, and `static_foo` doesn't work.
/// The `global` function resolves fine though.
fn correct() {
    global();
    let new_foo: Foo = Foo::new();
    new_foo.method();
    let static_result = Foo::static_foo();
}

/// This does not compile, but go to definition on `new`, `method`, and `static_foo` work.
/// The `Foo` type is still broken and the `global` function resolves fine.
fn incorrect() {
    global();
    let new_foo: Foo = new();
    method(new_foo);
    let static_result = static_foo();
}
```

**Comment by ta32** [comment]
please support rust wasam in the rust plugin. I dont want to keep invoking things from the command line. There should be a build and run tests command template just like there is for cargo.
