### ISSUE TITLE
Support deprecation attributes

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#3564]
There are two way to mark code as deprecated: `#[deprecated]` for general code and `#[rustc_deprecated]` for code in std. It would be cool to provide some code insights features like java/kotlin/etc. support already provides

* [x] Annotate usage of deprecated code
* [x] Take into account `#[allow(deprecated)]` to suppress the corresponding warnings
* [x] Change text attributes in completion for deprecated elements
