### ISSUE TITLE
Enable new macro expansion system by default

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#3628]
We decided to merge the new macro expansion system (introduced in #3015) but not enable it by default. There is an option to enable it:
![image](https://user-images.githubusercontent.com/2539310/58436688-4f633c80-80cf-11e9-9bcf-0f81bf30f46b.png)

Why new expansion engine is better?
* it makes possible to support `impl` blocks and `mod` declarations generated by declarative macros, i.e. if some methods are inside `impl` block generated by macro call, the plugin makes name resolution and completions for these methods as expected. Ability to make proper name resolution for `mod` declarations provides proper name resolution and completion for crates like tokio, async-std, reqwest, etc.
* it significantly decreases memory consumption that should speed up name resolution/completion operations on average
* if an item is declared in some macro call, the plugin can navigate you inside macro call on `Go to definition` action
* find usages works for macro calls arguments
* the plugin provides better completion inside macro calls
* the plugin provides [semantic highlighting](https://github.com/intellij-rust/intellij-rust/pull/4640) inside macro calls

To enable by default we have to handle:
- [x] UI freezes & memory consumption during expansion (IDEA's default 768mb should be enough) #3653
- [ ] UI blinking during expansion (dumb/smart mode switches)
- [x] Internal files with expansions are still visible sometimes (e.g. ctrl+shift+B)
- [x] Make a better progress bar filling #3945
- [x] Disable inspections/annotators while expanding macros #3660
- [x] https://github.com/intellij-rust/intellij-rust/issues/3692
- [x] Compress expansion files #3968
- [x] Speed up indexing #4355
- [ ] Long scanning phase (`O(project file count)`) after creation of new expansion file
- [ ] Long validation of macro expansions after project re-open or git branch switch or cargo deps change etc

After enabling it by default, these issues should be closed: #955 #2128 #2383 #2615 #2625 #2787 #2902 #3006 #3087 #3155 #3238 #3259 #3468 #3487 #3560 #3587 #3590 #3628 #3859 #4063 #4153 #4224 #4310 #4314 #4328 #4340 #4389 #4519 #4585 #4614 #4627 #4826 #5088 #5127 #5154 #5246 #5248 #5263 #5278 #5300 #5346 #5461 #5686 ...TODO

**Comment by panstromek** [comment]
There are still some hiccups that seems to be related to the new expansion system, even though I am not sure.

 1. Seems like if I close the window with rust plugin right after start during indexing, it will somehow break other windows. When I opened WebStorm, today, it opened 4 of my projects, so I close the one that I don't need but that one included some Rust, so it was still indexing and probably expanding macros. This resulted in broken syntax highlighting in JavaScript in other (non rust project) windows. The problem was gone after restart.

 2. Very similar problem. It happened to me on one occasion, I was waiting for indexing/expanding at the start but it was super slow. So I looked at other (non-rust) windows, and there was a blinking progress bar (something like what happens when you externally change some files with a script and IDEA starts reindexing them), so it seems like expanding macros somehow invalidates indexes for other windows, so they all start reindexing again, but they maybe block each other?? Anyway, the result was that not much was happening and they were all just blinking 😄 It seems like this problem is on the list, but I was not sure if you've seen multiple open projects interact in this way.

All of this happened in WebStorm EAP 19.3.2, which is also unstable by itself, but I don't think that is related.

I assume you are aware of these problems, but If you don't, I can investigate some more when I get some more time 😉

**Comment by Kobzol** [comment]
I met similar window problems. Sometimes when I close CLion during (or after) macro indexing, when I open it again it opens two windows, half of the UI is in the first one, half in the other one and I have to  delete the `workspace.xml` file for it to start working. I'm not sure if it's caused by the macro parsing, but it happens to me repeatedly on 2 different computers, only in CLion on Rust projects with the experimental macro engine.
