### ISSUE TITLE
Improve backtrace filters

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#4514]
## Environment

* **IntelliJ Rust plugin version:** 0.2.107.2757-193-nightly
* **Rust toolchain version:** 1.38.0 (625451e37 2019-09-23) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2019.3 EAP Ultimate Edition (IU-193.4099.13)
* **Operating system:** macOS 10.13.6

## Problem description
Quite a lot of lines of Rust backtrace don't have a link to sources although a user has them.
To improve that we should support the following cases:
* [ ] better process fully qualified names to stdlib items (red cases)
* [ ] understand relative paths to stdlib sources (blue cases)
* [ ] understand paths to sdtlib sources start with `/rustc/commit-hash` prefix (green cases)
* [ ] parse `<structPath as traitPath>::method` (violet case). It also may be useful in profiler
* [ ] understand extern function calls that don't have module prefix (oragne case)

<img width="930" alt="Screen Shot 2019-10-10 at 09 57 46" src="https://user-images.githubusercontent.com/2539310/66547599-420f9180-eb48-11e9-9785-1655759412e7.png">

## Steps to reproduce
To get similar backtrace on your machine just run the test from the following code
```rust
#[test]
fn foo() {
   assert_eq!(1, 2);
}
```
```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
   9: project::foo
             at src/main.rs:5
  10: project::foo::{{closure}}
             at src/main.rs:4
  11: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  14: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
  15: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
  16: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1408
```

**Comment by flying-sheep** [comment]
Also for Java backtraces, internal calls are collapsed by default. That would be nice here as well! Should be in [ConsoleFoldingConfigurable](https://github.com/joewalnes/idea-community/blob/master/platform/lang-impl/src/com/intellij/execution/console/ConsoleFoldingConfigurable.java) or so.

**Comment by Kobzol** [comment]
@Undin Fully qualified (stdlib) paths should now work, I couldn't simulate stdlib relative paths (`at src/...`) with Rust 1.47.
