### ISSUE TITLE
Support panic_handler attribute

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#5432]
## Environment

* **IntelliJ Rust plugin version:** 0.2.123.3110-201-nightly
* **Rust toolchain version:** 1.45.0-nightly (a74d1862d 2020-05-14) x86_64-apple-darwin
* **IDE name and version:** IntelliJ IDEA 2020.1.1 Ultimate Edition (IU-201.7223.91)
* **Operating system:** macOS 10.13.6

## Problem description
In `no_std` environment, you have to provide your own [panic handler](https://doc.rust-lang.org/nomicon/panic-handler.html). Currently, the plugin knows nothing about it. It would be cool to add some knowledge about it into the plugin.

More precisely:
* [ ] Complete `panic_handler` attribute. Ideally, we should add it into completion only when `no_std` attribute exists
    ![image](https://user-images.githubusercontent.com/2539310/82763387-f3311680-9e0f-11ea-9338-149353a6d47f.png)
* [ ] Highlight usage of `panic_handler` when there isn't `no_std` attribute as compilation error. The corresponding error annotation can provide quick fix to add `no_std` attribute.
    ![image](https://user-images.githubusercontent.com/2539310/82763901-95063280-9e13-11ea-8dff-8bede8048d2c.png)

* [ ] Check the signature of the corresponding function. It should have only one argument with `&PanicInfo` type and `!` as returning type. The corresponding error annotation may also provide quick fix to fix the signature
    ![image](https://user-images.githubusercontent.com/2539310/82763905-a2232180-9e13-11ea-9ad8-d7564f8c9f18.png)

* [ ] (advanced) check that there is only single panic handler function in the whole application. Note, libraries can also provide own panic handler. This feature also covers the second point because `std` crate of stdlib provides its own [panic hander](https://github.com/rust-lang/rust/blob/master/src/libstd/panicking.rs#L345-L348). Note, correct support of this feature requires the support of `cfg_attr`

## Steps to reproduce
```rust
#![no_std]

use core::panic::PanicInfo;

#[panic_handler]
fn panic(_: &PanicInfo) -> ! {
    loop {}
}

fn main() {
}
```

**Comment by ratijas** [comment]
I disagree that panic_handler attribute should be added to suggestions only when no_std attribute exists. Instead, I'd say include it always, but !..

 - Highlight the usage of panic_handler in a crate without no_std attribute as an error.
 - On Alt+Enter suggest add no_std attribute if not present.

**Comment by Undin** [comment]
@ratijas probably, it's even easy for implementation.
> * Highlight the usage of panic_handler in a crate without no_std attribute as an error.
> * On Alt+Enter suggest add no_std attribute if not present.

See the second point in the issue
