### ISSUE TITLE
Cargo.toml improvements

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#5440]
Meta-issue about various `Cargo.toml`-related improvements.

- [ ] Parse crate information from the local index (https://github.com/intellij-rust/intellij-rust/issues/2757)
- [ ] Provide completion for features of a crate (https://github.com/intellij-rust/intellij-rust/issues/4693 https://github.com/intellij-rust/intellij-rust/issues/4455)
- [ ] Provide completion for dependency attributes (https://github.com/intellij-rust/intellij-rust/issues/4455)
- [ ] Provide completion for local dependency paths (https://github.com/intellij-rust/intellij-rust/issues/4455 https://github.com/intellij-rust/intellij-rust/issues/4144)
- [ ] Check that crates in `[dependencies]` exist and have a valid version (https://github.com/intellij-rust/intellij-rust/issues/4456 https://github.com/intellij-rust/intellij-rust/issues/1778 https://github.com/intellij-rust/intellij-rust/issues/3655)
- [ ] Expand dependency version (https://github.com/intellij-rust/intellij-rust/issues/4869)
- [ ] Avoid macro indexing during benign `Cargo.toml` changes (https://github.com/intellij-rust/intellij-rust/issues/5062)
- [ ] Warn about missing dependencies and add dependency to `Cargo.toml` if it's missing (https://github.com/intellij-rust/intellij-rust/issues/4092)

**Comment by Kobzol** [comment]
The speed is indeed problematic and it's blocking progress a bit I think. https://github.com/intellij-rust/intellij-rust/pull/4873 there are problems with parsing the local index however. I would implement new stuff on top of the API, but make it easy to change the crate resolver in the future. I introduced such abstraction in https://github.com/intellij-rust/intellij-rust/pull/5439.
