### ISSUE TITLE
Rust support in MSVC LLDB

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#5632]
This meta issue is aimed to track the progress of improving Rust support in [MSVC LLDB](https://blog.jetbrains.com/clion/2019/06/clion-2019-2-eap-msvc-debugger-unused-includes-check-and-more/#msvc_debug).

#### IDE support
- [x] CLion #5535
- [ ] IDEA Ultimate, AppCode, RubyMine #5610

#### Rendering
- [ ] Render enums properly
- [ ] Render primitive types properly
- [ ] Render `&str` properly

#### Other
- [ ] Set up pretty-printers tests on Windows

**Comment by zhuxiujia** [comment]
will support Clion  with MSVC LLDB ???

**Comment by Undin** [comment]
@zhuxiujia MSVC LLDB in CLion works since #5535

**Comment by harry1453** [comment]
When you're using the MSVC rust toolchain and MinGW is configured as the toolchain in CLion, it's not possible to debug without setting Visual Studio as the default toolchain. Is there a way to tell CLion which toolchain to use for rust? If you have multiple CLion projects open, changing the default affects all of them so I want to avoid this.

**Comment by ortem** [comment]
@harry1453 If you have a CMake project and a Rust project and want to use different CLion toolchains for them, you can try to do the following:
- set CLion toolchain for Rust as a default one (top of the [Toolchains list](https://www.jetbrains.com/help/clion/toolchains.html))
- set another CLion toolchain in [CMake profile](https://www.jetbrains.com/help/clion/cmake-profile.html) for your CMake project

Please let us know if it helps.
