### ISSUE TITLE
asm! macro meta issue

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#6045]
This is a meta issue about support for the new `asm!` macro.

Implement:
- [ ] parsing (https://github.com/intellij-rust/intellij-rust/pull/5928)
- [ ] argument highlight + check
- [ ] completion
- [ ] inference
- [ ] control flow (https://github.com/intellij-rust/intellij-rust/issues/5815)
- [ ] surround with unsafe (https://github.com/intellij-rust/intellij-rust/issues/6044)

Original issue: https://github.com/intellij-rust/intellij-rust/issues/1940
