### ISSUE TITLE
Rework Cargo project structure loading

### ISSUE THREAD

**Issue by Undin** [intellij-rust/intellij-rust#6104]
Cargo project structure loading was designed to be almost invisible to users. In the beginning, it called only `cargo metadata` to retrieve project structure and it's very quick. As a result, automatic project structure reloading was turned on.

But later we found out that we need to run some long operations like compile (part of) project to get compile time info (`OUT_DIR` variable, `cfg` attributes generated by build script, etc.).

Also, the platform support of build tools is also improving constantly and now the current platform contains `Sync` tool window to show result of project importing, common settings of automatic project structure reloading (it may be essential when your reloading operation may compile the whole project), etc.

So we want to rework some part of cargo project structure loading to properly support new needs from one side and new platform features from another side.

This issue is a tracking meta issue to show what we want to change and what we've already done. Note, some items are quite technical and are not visible to users.
* [ ] Create `CargoSyncTask` instead of using `org.rust.openapiext.AsyncTasksKt#runAsyncTask`
* [ ] Use platform read/write lock instead of `org.rust.stdext.AsyncValue` to keep project info
* [ ] Retrieve metadata from stdlib. Currently, we have a hardcoded info about stdlib. It should support proper edition detection in stdlib and get info about dependencies of stdlib
* [ ] Convert `org.rust.cargo.evaluate.build.scripts` experimental feature to user visible setting
* [ ] Take into account project loading settings (see `Preferences | Build, Execution, Deployment | Build Tools`)
* [ ] Show floating button to reload project structure if it's outdated
* [ ] Support platform `Load Changes` action
* [ ] Support `Sync` tool window to show results of project loading (including failed compilation if it's needed) #4699 #4546
* [ ] Don't invoke project reloading on non-important change like the addition of space in `Cargo.toml` #5062
* [ ] Don't invoke project reloading twice after: the first one after `Cargo.toml` change and the second one after `Cargo.lock` change because of previous corresponding changes in `Cargo.toml`

**Comment by tdrozdowski** [comment]
Will this include restoring the code completion of files generated and out into the OUT_DIR?  Its impossible to work with Tonic/Prost (gRPC) with he latest builds - nothing has worked since 126.

**Comment by Undin** [comment]
@tdrozdowski looks like it's an unknown issue and I think it should be fixed separately even without changes described in this issue. Could you file a new issue and attach code example to reproduce it?
Note, make sure that `org.rust.cargo.evaluate.build.scripts` option in `Experimental Features` is enabled and you project is refreshed after it. Also, I checked [gcp](https://github.com/hyperium/tonic/tree/37f6733f85a42e828c124026c3a0f21919549b12/examples/src/gcp) example from tonic crate, and it works for me with the latest nightly plugin

**Comment by tdrozdowski** [comment]
This doesn't work when you have a project setup with a Cargo workspace (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html).  There are at least already two separate issues already logged against this - it's been broken since 126.

Yes, I have every experimental feature enabled related to Rust.  I've tried invalidating caches, reinstalling, etc - same results.

Steps:
Create a cargo workspace.
Create a crate project inside the workspace that includes the protos from Tonic/Prost - build and compile
Create a new crate project inside the same workspace that references the proto crate from above

Note that you cannot implement and client/server traits in the new project and that all code completion otherwise fails.

I cannot share the project as it is not open source.

Previous issues:
#5878 which was later attached to #5861
