### ISSUE TITLE
Name resolution 2.0

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#6217]
New name resolution algorithm (aka name resolution 2.0) is an effort to rewrite part of the name resolution code in order to better support complex glob-imports/reexports and [resolve](https://github.com/rust-lang/rfcs/blob/master/text/1561-macro-naming.md) of [macros 2.0](https://github.com/rust-lang/rfcs/blob/master/text/1584-macros.md).

## Name resolution 1.0
Current name resolution algorithm (aka name resolution 1.0) uses [traditional lazy approach](https://rust-analyzer.github.io/blog/2020/07/20/three-architectures-for-responsive-ide.html#map-reduce), which roughly can be described as "going scopes upwards". It works in most cases and is pretty fast. The main downside is that it is some approximation, not necessarily correct by any means.

## Name resolution 2.0
New name resolution algorithm consists of two parts:
* Collect phase, where for each crate we build a special structure called `CrateDefMap`. This structure for each module of the crate stores a set of all items available in this module. It includes explicitly declared items, imported items, and items expanded from macros.
  * To built `CrateDefMap` we first collect all explicitly declared items, imports and macro calls. Then iteratively expand macros and resolve imports, until something changes. This is called fixed-point iteration algorithm which is used in both `rustc` and `rust-analyzer`.
  * Fixed-point iteration is not incremental, so we have to rebuild `CrateDefMap` after any change which might affect resolve (e.g. adding new item)
* Resolve phase, where we use built `CrateDefMap` to do actual resolve.

Please note that new resolve will be used only for top-level items (so resolve of local variables or anything related to type inference is not changed by new resolve).

**Comment by dima74** [comment]
Next steps after #6241 merged:

- [ ] Tests
  - [ ] Add resolve tests which work only with new resolve (#6297)
  - [ ] Run all existing resolve tests on CI (#6317)
  - [ ] Add tests for specific functionality of new resolve (caching/updating `DefMap`s)
- [ ] Memory optimizations
  - [ ] Store `DefMap`s under soft references
  - [ ] Unite `PerNs` and `VisItem` when there is only one item (with namespace) with specific name
  - [ ] Research why half of all `VisItem`s are duplicated (equal, but different objects)
  - [ ] (?) Save `DefMap`s to disk
- [ ] Add option to settings for enabling new resolve
- [ ] Filter/sort private items in completion
- [ ] Propagate expanded macro def to child modules
- [ ] (?) Expand macros at collect phase, if possible
