### ISSUE TITLE
ML code completion for Rust

### ISSUE THREAD

**Issue by ortem** [intellij-rust/intellij-rust#6411]
IntelliJ-based IDEs provide a ranking mechanism for code completion based on machine learning. This mechanism [is already supported](https://blog.jetbrains.com/idea/2020/10/intellij-idea-2020-3-eap5/) for Java and some other languages. It would be great to support this for Rust as well.

TODO:
- [ ] Basic support of ML ranking for Rust code completion
- [ ] Provide Rust-specific element features using `com.intellij.codeInsight.completion.ml.ElementFeatureProvider`
  - [ ] Consider if element is a keyword
  - [ ] Consider element's PSI type
  - [ ] Consider element's origin (stdlib or not)
  - [ ] Consider expected argument names based on parameter names
  - [ ] Consider expected argument types based on parameter types
- [ ] Provide Rust-specific context features using `com.intellij.codeInsight.completion.ml.ContextFeatureProvider`
- [ ] Enable ML ranking by default

To be continued.
