### ISSUE TITLE
Add Cargo.toml refresh popup

### ISSUE THREAD

**Issue by mahkoh** [intellij-rust/intellij-rust#6424]
Intellij has the following feature: https://blog.jetbrains.com/idea/2020/01/intellij-idea-2020-1-eap/#maven_and_gradle_importing_updates

Please add the same feature for Cargo.toml changes.

* [x] Implement `ExternalSystemProjectAware` and move all current logic from `CargoTomlWatcher`. It should automatically solve issues like #5062 #8779. #8919
* [x] Provide proper icon for floating button when a project model is not up-to-date (via `ExternalSystemIconProvider` EP) #8980
* [ ] Move `Preferences | Languages & Frameworks | Rust | Cargo` settings to `Preferences | Build, Execution, Deployment | Build Tools` #9012
* [x] Trigger project model update on changes in [build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) #8987
* [x] Trigger project model update on changes in [Cargo config](https://doc.rust-lang.org/cargo/reference/config.html) (#8114) and [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) #8960
* [ ] Enable by default #9012

**Comment by Undin** [comment]
@mahkoh Part of #6104
