### ISSUE TITLE
Code analysis with crates local index

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#6463]
#### Completion
 - [ ] Features

#### Inspections
 - [ ] Crate is not found
 - [ ] Crate is found but version is not
 - [ ] Crate version is yanked
 - [ ] Version should not be empty
 - [ ] Feature is not found in crate

#### Suggestions
 - [ ] Suggest to bump version it if it is not newest
 - [ ] Suggest to bump version if it is yanked
 - [ ] Suggest to bump version to nearest one if a feature is not present in this one

#### Actions
- [ ] Update all dependencies to the latest major/minor/patch version

**Comment by Kobzol** [comment]
It would be great if versions were also auto-completed inside the complex dependency specification:
```toml
[dependencies]
serde = { version = "/*here version is not completed*/" }
```
