### ISSUE TITLE
Improve Change Signature refactoring

### ISSUE THREAD

**Issue by Kobzol** [intellij-rust/intellij-rust#6744]
Improve the Change Signature refactoring introduced in #5944.

- [ ] Allow specifying default values for parameters.
- [ ] Add support for suggested refactoring (introduced for local variables in https://github.com/intellij-rust/intellij-rust/pull/5913).
- [ ] Add function parameter from function call.
- Support `extern`?
- Allow changing type parameters and `where` clauses?

**Comment by Undin** [comment]
> Sometimes it would be super handy if @intellijrust had a refactoring to add a new type or lifetime parameter to a struct (an make all the necessary changes to surrounding code).
 
From https://twitter.com/wezm/status/1355047090087288832.

Looks like as part of Change Signature refactoring

**Comment by Kobzol** [comment]
I suppose that change signature is only for functions, or not? For structs we probably need a separate type of refactoring.

**Comment by sassman** [comment]
Would be very handy to have it for Structs as well.
