### ISSUE TITLE
TOML code insight & JSON schemas

### ISSUE THREAD

**Issue by avrong** [intellij-rust/intellij-rust#7180]
The current issue contains ideas of improvements to the TOML plugin code insight, many of them becoming available with JSON schemas support.

### Intentions
- [ ] Expand inline table
- [ ] Shrink full table into inline
- [ ] Move key segment into table header (?)
- [ ] Escape key
- [ ] Unescape key (if possible?)
- [ ] Rename key with auto-escaping

### Completion
- [ ] Key completion
- [ ] Correct default type values insertion
- [ ] Value enum completion

### Inspections
- [ ] Invalid key name
- [ ] Invalid value type
- [ ] Incorrect value (enum)
- [ ] Incorrect value (regexp)
- [ ] Duplicated keys in a table
- [ ] Deprecated property

### Schemas
- [ ] Cargo.toml schema
- [ ] .cargo schema
