### ISSUE TITLE
Rewrite auto import using CrateDefMap from Name Resolution 2.0

### ISSUE THREAD

**Issue by vlad20012** [intellij-rust/intellij-rust#7558]
`CrateDefMap`-based auto-import should be much faster and more accurate than current stub index-based implementation. Also, with `CrateDefMap` it would be trivial to implement auto-import for declarative and procedural macros (#3690)

* [x] Path auto-import #7914
* [x] Traits auto-import #8029
* [x] UFCS paths #8054
* [x] In refactorings and inspections (`RsImportHelper`, etc) #8083
* [x] Sort resolved paths before unresolved ones #8291
* [x] Wait for new resolve support in doctests
* [ ] Remove old auto-import code
