### ISSUE TITLE
Integrate more actions with `Actions on Save`

### ISSUE THREAD

**Issue by mchernyavsky** [intellij-rust/intellij-rust#7765]
IntelliJ IDEs received [Actions on Save](https://www.jetbrains.com/help/idea/2021.2/saving-and-reverting-changes.html#actions-on-save) feature in 2021.2 release. This feature generalizes different actions in different plugins/IDEs that can be triggered when IDE saves changes.

Some potential candidates for `Actions on Save` in IntelliJ Rust:
- [ ] `rustfmt` https://github.com/intellij-rust/intellij-rust/issues/7705
- [ ] `cargo check` https://github.com/intellij-rust/intellij-rust/issues/5542
- [ ] `cargo fix`
- [ ] `clippy` https://github.com/intellij-rust/intellij-rust/issues/5542
- [ ] `clippy --fix` https://github.com/intellij-rust/intellij-rust/issues/7764
- [ ] ???

**Comment by maxim-banaev** [comment]
https://youtrack.jetbrains.com/issue/CPP-28231

**Comment by OSSDeveloper** [comment]
Hi,

      Below options/commands are needed apart from those you mentioned:-

1. rustfmt(already mentioned in your list)
2. rustc <provision to specify file with full/relative path>- to compile the project
3. cargo run <provision to specify file with full/relative path>- to run the project
4. cargo doc - go update the documentation

With these options, the development turn-around time can be reduced considerably.
