### ISSUE TITLE
Support "Intention preview"

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#9561]
## Environment

* **IntelliJ Rust plugin version:** 0.4.182.4945-222-nightly
* **Rust toolchain version:** 1.66.0-nightly (8ce3204af 2022-09-30) x86_64-unknown-linux-gnu
* **IDE name and version:** CLion 2022.2.4 (CL-222.4345.21)
* **Operating system:** Linux 6.0.1-zen2-1-zen
* **Macro expansion:** enabled
* **Additional experimental features:** org.rust.cargo.emulate.terminal, org.rust.macros.proc

## Problem description
Intention preview will be [enabled by default in 2022.3](https://blog.jetbrains.com/idea/2022/09/intellij-idea-2022-3-eap/#Intention_action_preview_enabled_by_default), so it is worth to check our intentions and fix them if necessary. Currently we may show preview only for quick-fixes, for intentions there will be no preview because of [`RsElementBaseIntentionAction`](https://github.com/intellij-rust/intellij-rust/blob/8c9d70be685f25dfbd6031e37a18f30314478b54/src/main/kotlin/org/rust/ide/intentions/RsElementBaseIntentionAction.kt#L46) specifity. So the plan is:

* [x] Disable preview when it is not needed, e.g. intentions/quick-fixes which create new files and don't modify code #9562
* [x] Find quick-fixes with incorrect preview and fix them #9699
* [x] Fix `RsElementBaseIntentionAction` so that preview will be generated for intentions
* [x] Find intentions with incorrect preview and fix them #9641

Known problems:
* [x] `Create module file` #9560
* [x] `Rename to` #9450
* [x] `Expand dependency specification` (toml) #9431
* [x] `Add definition to trait` #9693

List of intentions/quick-fixes which currently don't have preview, but it can be added:

- [ ] `CreateFunctionIntention`, `CreateStructIntention`, `CreateTupleStructIntention`
- [ ] `AddImportForPatternIntention` when one candidate
- [ ] `AddImportIntention`
- [ ] `IntroduceLocalVariableIntention`
- [ ] `RenameFix`

**Comment by Undin** [comment]
I think we should close it only after fixing all remaining cases
