### ISSUE TITLE
Meta: intra-doc links

### ISSUE THREAD

**Issue by dima74** [intellij-rust/intellij-rust#9755]
Meta issue for [intra-doc links](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html)

* [ ] Parsing
  * [x] `[text](link)` - #7353
  * [x] `label: link` - #7353
  * [x] `[link]` - #9686
  * [ ] Links in URL format like `[get]: ../../std/vec/struct.Vec.html#method.get`
* [ ] Code insight
  * [x] Basic resolve and completion
  * [ ] Take into account disambiguator during resolve
  * [ ] Completion for (private?) macros #9749
  * [ ] Resolve markdown label reference `[label]` when there is corresponding label definition `[label]: link`

**Comment by laralove143** [comment]
#10502 should be added to this list
